trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: cifar100-block-lr-0.005-s3
  max_steps: 10000
  val_check_interval: 500
model:
  model_name: vit-b16-224-dino
  training_mode: block
  optimizer: sgd
  lr: 0.005
  split: 3
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
data:
  num_classes: 200
  dataset: cub200
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max
